language: scala
scala:
  - 2.11.8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
install: true

script:
  - sbt clean coverage test coverageReport

after_success:
  - sbt coveralls
